FROM docker.m.daocloud.io/library/python:3.12-slim

WORKDIR /app

RUN pip config set global.index-url https://pypi.tuna.tsinghua.edu.cn/simple

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY . .

EXPOSE 8501

CMD ["streamlit", "run", "app/ui/streamlit_app.py", \
     "--server.address", "0.0.0.0", \
     "--server.port", "8501"]